package com.scm.promotion

import com.scm.promotion.model.Item
import java.util.List

rule "SkuCode A Offers"
  when
  $item1 : Item( skuCode == "A" && reqQuantity >= 3) 
  then
  $item1.setOfferQuantity(3);
  $item1.setOfferPrice(130.00);
  
end
rule "SkuCode B Offers"
  when
  $item1 : Item( skuCode == "B" && reqQuantity >= 2)
  then
  $item1.setOfferQuantity(2);
  $item1.setOfferPrice(45.00);
end
rule "SkuCode C & D Offers"
  when
  $item1 : Item( skuCode == "C" && reqQuantity>=1) 
  $item2 : Item( skuCode == "D" && reqQuantity>=1 ) 
  then
  $item1.setOfferQuantity(1);
  $item1.setOfferPrice(0.00);
  
  $item2.setOfferQuantity(1);
  $item2.setOfferPrice(30.00);
end